"use client";

import { Button } from "@/components/ui/Button";
import { TabList, TabPanel, TabTrigger, Tabs } from "@/components/ui/Tabs";
import type { ShaderManifest, UniformDef } from "@/lib/shader-registry";
import { useStore } from "@/lib/store";
import { useCallback } from "react";

interface ExportDrawerProps {
	manifest: ShaderManifest;
	fragSrc: string;
	shareId?: string;
}

function getDefaultValue(def: UniformDef): number | number[] {
	return def.default;
}

function buildComponentTSX(
	manifest: ShaderManifest,
	fragSrc: string,
	uniforms: Record<string, number | number[]>,
): string {
	const uniformEntries = manifest.uniforms
		.map((def) => {
			const val = uniforms[def.name] ?? getDefaultValue(def);
			return `  ${def.name}: ${JSON.stringify(val)},`;
		})
		.join("\n");

	return `// Auto-generated by Shader Studio — ${new Date().toISOString().slice(0, 10)}
// Requires: @/lib/runtime (createRuntime, ShaderManifest)

"use client";
import { useEffect, useRef } from "react";
import { createRuntime, type ShaderManifest } from "@/lib/runtime";

const FRAG_SRC = ${JSON.stringify(fragSrc)};

const MANIFEST: ShaderManifest = ${JSON.stringify(manifest, null, 2)};

const INITIAL_UNIFORMS = {
${uniformEntries}
};

export function ${toPascalCase(manifest.id)}() {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const runtime = createRuntime(canvas, {
      fragSrc: FRAG_SRC,
      manifest: MANIFEST,
      initial: INITIAL_UNIFORMS,
    });
    return () => runtime.destroy();
  }, []);

  return (
    <canvas
      ref={canvasRef}
      style={{ width: "100%", height: "100%" }}
      aria-label="${manifest.label} shader"
    />
  );
}
`;
}

function toPascalCase(id: string): string {
	return id
		.split("-")
		.map((s) => s.charAt(0).toUpperCase() + s.slice(1))
		.join("");
}

function buildAIPrompt(
	manifest: ShaderManifest,
	fragSrc: string,
	uniforms: Record<string, number | number[]>,
): string {
	const uniformLines = Object.entries(uniforms)
		.map(([k, v]) => `  ${k}: ${JSON.stringify(v)}`)
		.join("\n");

	return `You're helping customize a WebGL fragment shader from Shader Studio.

SHADER: ${manifest.label} (id: ${manifest.id}, v${manifest.version})
CURRENT UNIFORMS:
${uniformLines}

FULL GLSL:
\`\`\`glsl
${fragSrc}
\`\`\`

GOAL: [describe what you want to change]

RULES:
- Keep the runtime API (createRuntime from @/lib/runtime) unchanged.
- Prefer additive changes; don't refactor working code.
- Every uniform must have an @uniform annotation comment.
- WebGL 1 only (no \`texture()\`, no \`in\`/\`out\`, no multiple render targets).`;
}

interface CodeBlockProps {
	code: string;
	label: string;
}

function CodeBlock({ code, label }: CodeBlockProps) {
	const handleCopy = useCallback(async () => {
		await navigator.clipboard.writeText(code);
	}, [code]);

	return (
		<div className="flex flex-col gap-2 min-w-0">
			<div className="flex items-center justify-between gap-2 min-w-0">
				<span className="text-xs text-neutral-500 truncate min-w-0">{label}</span>
				{/* Copy button: min-h-[44px] meets tap target */}
				<Button variant="outline" size="sm" onClick={handleCopy} className="shrink-0">
					Copy
				</Button>
			</div>
			{/*
			  overflow-x-auto: long lines scroll horizontally inside the block.
			  word-break: break-word: very long tokens (e.g. base64 strings) wrap
			  rather than pushing the block wider than the viewport.
			  max-h-48 keeps the block from dominating the drawer.
			*/}
			<pre className="overflow-x-auto rounded-md bg-neutral-900 p-3 text-xs text-neutral-300 border border-neutral-800 max-h-48 min-w-0">
				<code style={{ wordBreak: "break-word", whiteSpace: "pre-wrap" }}>{code}</code>
			</pre>
		</div>
	);
}

export function ExportDrawer({ manifest, fragSrc, shareId: _shareId }: ExportDrawerProps) {
	const uniforms = useStore((s) => s.uniforms);

	const componentTSX = buildComponentTSX(manifest, fragSrc, uniforms);

	const configJSON = JSON.stringify(
		{
			shaderId: manifest.id,
			uniforms: manifest.uniforms.reduce<Record<string, number | number[]>>((acc, def) => {
				acc[def.name] = uniforms[def.name] ?? getDefaultValue(def);
				return acc;
			}, {}),
		},
		null,
		2,
	);

	const aiPrompt = buildAIPrompt(manifest, fragSrc, uniforms);

	return (
		<div className="border-t border-neutral-800 bg-neutral-950 p-4 min-w-0 overflow-hidden">
			<h2 className="mb-3 text-sm font-semibold text-neutral-200">Export</h2>
			<Tabs defaultTab="component">
				{/* Tab row is scrollable so it never overflows at 320px */}
				<TabList className="mb-3 overflow-x-auto scrollbar-none">
					<TabTrigger id="component">Component TSX</TabTrigger>
					<TabTrigger id="config">Config JSON</TabTrigger>
					<TabTrigger id="ai-prompt">AI Prompt</TabTrigger>
				</TabList>
				<TabPanel id="component">
					<CodeBlock code={componentTSX} label="React component — paste into your project" />
				</TabPanel>
				<TabPanel id="config">
					<CodeBlock code={configJSON} label="Current uniform values as JSON" />
				</TabPanel>
				<TabPanel id="ai-prompt">
					<CodeBlock
						code={aiPrompt}
						label="Paste into Claude Code or similar to customize the shader"
					/>
				</TabPanel>
			</Tabs>
		</div>
	);
}
