"use client";

import { Button } from "@/components/ui/Button";
import { TabList, TabPanel, TabTrigger, Tabs } from "@/components/ui/Tabs";
import type { ShaderManifest, UniformDef } from "@/lib/shader-registry";
import { useStore } from "@/lib/store";
import { useCallback } from "react";

interface ExportDrawerProps {
	manifest: ShaderManifest;
	fragSrc: string;
	shareId?: string;
}

function getDefaultValue(def: UniformDef): number | number[] {
	return def.default;
}

function buildComponentTSX(
	manifest: ShaderManifest,
	fragSrc: string,
	uniforms: Record<string, number | number[]>,
): string {
	const uniformEntries = manifest.uniforms
		.map((def) => {
			const val = uniforms[def.name] ?? getDefaultValue(def);
			return `  ${def.name}: ${JSON.stringify(val)},`;
		})
		.join("\n");

	return `// Auto-generated by Shader Studio — ${new Date().toISOString().slice(0, 10)}
// Requires: @/lib/runtime (createRuntime, ShaderManifest)

"use client";
import { useEffect, useRef } from "react";
import { createRuntime, type ShaderManifest } from "@/lib/runtime";

const FRAG_SRC = ${JSON.stringify(fragSrc)};

const MANIFEST: ShaderManifest = ${JSON.stringify(manifest, null, 2)};

const INITIAL_UNIFORMS = {
${uniformEntries}
};

export function ${toPascalCase(manifest.id)}() {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const runtime = createRuntime(canvas, {
      fragSrc: FRAG_SRC,
      manifest: MANIFEST,
      initial: INITIAL_UNIFORMS,
    });
    return () => runtime.destroy();
  }, []);

  return (
    <canvas
      ref={canvasRef}
      style={{ width: "100%", height: "100%" }}
      aria-label="${manifest.label} shader"
    />
  );
}
`;
}

function toPascalCase(id: string): string {
	return id
		.split("-")
		.map((s) => s.charAt(0).toUpperCase() + s.slice(1))
		.join("");
}

function buildEmbedURL(shareId: string | undefined, manifest: ShaderManifest): string {
	const base = "https://shader-studio.vercel.app/s/";
	const id = shareId ?? manifest.id;
	return `${base}${id}`;
}

interface CodeBlockProps {
	code: string;
	label: string;
}

function CodeBlock({ code, label }: CodeBlockProps) {
	const handleCopy = useCallback(async () => {
		await navigator.clipboard.writeText(code);
	}, [code]);

	return (
		<div className="flex flex-col gap-2">
			<div className="flex items-center justify-between">
				<span className="text-xs text-neutral-500">{label}</span>
				<Button variant="outline" size="sm" onClick={handleCopy}>
					Copy
				</Button>
			</div>
			<pre className="overflow-auto rounded-md bg-neutral-900 p-3 text-xs text-neutral-300 border border-neutral-800 max-h-48">
				<code>{code}</code>
			</pre>
		</div>
	);
}

export function ExportDrawer({ manifest, fragSrc, shareId }: ExportDrawerProps) {
	const uniforms = useStore((s) => s.uniforms);

	const componentTSX = buildComponentTSX(manifest, fragSrc, uniforms);

	const configJSON = JSON.stringify(
		{
			shaderId: manifest.id,
			uniforms: manifest.uniforms.reduce<Record<string, number | number[]>>((acc, def) => {
				acc[def.name] = uniforms[def.name] ?? getDefaultValue(def);
				return acc;
			}, {}),
		},
		null,
		2,
	);

	const embedURL = buildEmbedURL(shareId, manifest);
	const embedSnippet = `<iframe\n  src="${embedURL}"\n  width="600"\n  height="400"\n  style="border:none;border-radius:8px"\n  title="${manifest.label}"\n></iframe>`;

	return (
		<div className="border-t border-neutral-800 bg-neutral-950 p-4">
			<h2 className="mb-3 text-sm font-semibold text-neutral-200">Export</h2>
			<Tabs defaultTab="component">
				<TabList className="mb-3">
					<TabTrigger id="component">Component TSX</TabTrigger>
					<TabTrigger id="config">Config JSON</TabTrigger>
					<TabTrigger id="embed">Embed</TabTrigger>
				</TabList>
				<TabPanel id="component">
					<CodeBlock code={componentTSX} label="React component — paste into your project" />
				</TabPanel>
				<TabPanel id="config">
					<CodeBlock code={configJSON} label="Current uniform values as JSON" />
				</TabPanel>
				<TabPanel id="embed">
					<CodeBlock code={embedSnippet} label="iframe embed snippet" />
					<p className="mt-2 text-xs text-neutral-600">
						Note: Share URL requires the Share button to be clicked first to generate a valid
						shareId.
					</p>
				</TabPanel>
			</Tabs>
		</div>
	);
}
