/**
 * Static shader registry. Generated by `pnpm gen:manifests` (scripts/generate-manifests.ts)
 * but hand-written for v0.1.
 *
 * Frag sources are inlined as static strings so no fetch is needed.
 * In v0.2 the generate-manifests script will produce this file automatically.
 */

export type StoragePrecision = "uint8" | "int16" | "float32";

export interface UniformDef {
	name: string;
	type: "float" | "vec2" | "vec3" | "vec4";
	range?: [number, number];
	default: number | number[];
	label: string;
	group: string;
	storage: StoragePrecision;
}

export interface ShaderManifest {
	id: string;
	version: number;
	label: string;
	description?: string;
	uniforms: UniformDef[];
}

export interface RegistryEntry {
	manifest: ShaderManifest;
	fragSrc: string;
}

import glassOrbFrag from "@/shaders/glass-orb/frag";
import glassOrbManifest from "@/shaders/glass-orb/manifest.json";

export const SHADER_REGISTRY: RegistryEntry[] = [
	{
		manifest: glassOrbManifest as ShaderManifest,
		fragSrc: glassOrbFrag,
	},
];

export function getRegistryEntry(id: string): RegistryEntry | undefined {
	return SHADER_REGISTRY.find((e) => e.manifest.id === id);
}
