/**
 * Static shader registry. Generated by `pnpm gen:manifests` (scripts/generate-manifests.ts)
 * but hand-written for v0.1.
 *
 * Frag sources are inlined as static strings so no fetch is needed.
 * In v0.2 the generate-manifests script will produce this file automatically.
 */

export type StoragePrecision = "uint8" | "int16" | "float32";

export interface UniformDef {
	name: string;
	type: "float" | "vec2" | "vec3" | "vec4";
	range?: [number, number];
	default: number | number[];
	label: string;
	group: string;
	storage: StoragePrecision;
}

export interface Preset {
	name: string;
	description?: string;
	uniforms: Record<string, number | number[]>;
}

export type ShaderCategory =
	| "primitives"
	| "fractals"
	| "tpms"
	| "attractors"
	| "gradients"
	| "patterns"
	| "noise";

export const CATEGORY_LABELS: Record<ShaderCategory, string> = {
	primitives: "Primitives",
	fractals: "Fractals",
	tpms: "Minimal Surfaces",
	attractors: "Attractors",
	gradients: "Gradients",
	patterns: "Patterns",
	noise: "Noise",
};

export interface ShaderManifest {
	id: string;
	version: number;
	label: string;
	description?: string;
	category?: ShaderCategory;
	tags?: string[];
	uniforms: UniformDef[];
	presets?: Preset[];
}

export interface RegistryEntry {
	manifest: ShaderManifest;
	fragSrc: string;
}

import glassOrbFrag from "@/shaders/glass-orb/frag";
import glassOrbManifest from "@/shaders/glass-orb/manifest.json";
import gyroidFrag from "@/shaders/gyroid/frag";
import gyroidManifest from "@/shaders/gyroid/manifest.json";
import julia3dFrag from "@/shaders/julia-3d/frag";
import julia3dManifest from "@/shaders/julia-3d/manifest.json";
import mandelbulbFrag from "@/shaders/mandelbulb/frag";
import mandelbulbManifest from "@/shaders/mandelbulb/manifest.json";
import strangeAttractorFrag from "@/shaders/strange-attractor/frag";
import strangeAttractorManifest from "@/shaders/strange-attractor/manifest.json";

export const SHADER_REGISTRY: RegistryEntry[] = [
	{
		manifest: glassOrbManifest as unknown as ShaderManifest,
		fragSrc: glassOrbFrag,
	},
	{
		manifest: mandelbulbManifest as ShaderManifest,
		fragSrc: mandelbulbFrag,
	},
	{
		manifest: gyroidManifest as ShaderManifest,
		fragSrc: gyroidFrag,
	},
	{
		manifest: strangeAttractorManifest as ShaderManifest,
		fragSrc: strangeAttractorFrag,
	},
	{
		manifest: julia3dManifest as ShaderManifest,
		fragSrc: julia3dFrag,
	},
];

export function getRegistryEntry(id: string): RegistryEntry | undefined {
	return SHADER_REGISTRY.find((e) => e.manifest.id === id);
}
